export enum MessageTypes {
    ONE_TO_ONE_TEXT = 'ONE_TO_ONE_TEXT',
    ONE_TO_ONE_IMAGE = 'ONE_TO_ONE_IMAGE',
    GROUP_TEXT = 'GROUP_TEXT',
    GROUP_IMAGE = 'GROUP_IMAGE',
    GROUP_NEW_MEMBER_ADD = 'GROUP_NEW_MEMBER_ADD',
    GROUP_MEMBER_REMOVE = 'GROUP_MEMBER_REMOVE',
    GROUP_JOIN = 'GROUP_JOIN',
    GROUP_LEFT = 'GROUP_LEFT'
}