export enum WSNotificationTypes {
    SENT_ONE_TO_ONE_TEXT_MESSAGE='SENT_ONE_TO_ONE_TEXT_MESSAGE',
    ONE_TO_ONE_SENT_TEXT_CONFIRM='ONE_TO_ONE_SENT_TEXT_CONFIRM',
    SENT_GROUP_TEXT_MESSAGE='SENT_GROUP_TEXT_MESSAGE',
    RECEIVE_ONE_TO_ONE_TEXT_MESSAGE='RECEIVE_ONE_TO_ONE_TEXT_MESSAGE',
    RECEIVE_GROUP_TEXT_MESSAGE='RECEIVE_GROUP_TEXT_MESSAGE',
    RECEIVE_GROUP_TEXT_MESSAGE_CONFIRM='RECEIVE_GROUP_TEXT_MESSAGE_CONFIRM',
    ONE_TO_ONE_TEXT_MESSAGE_DR='ONE_TO_ONE_TEXT_MESSAGE_DR'
}
