export enum WSNotificationTypes {
    SENT_ONE_TO_ONE_TEXT_MESSAGE='SENT_ONE_TO_ONE_TEXT_MESSAGE',
    SENT_GROUP_TEXT_MESSAGE='SENT_GROUP_TEXT_MESSAGE',
    RECEIVE_ONE_TO_ONE_TEXT_MESSAGE='RECEIVE_ONE_TO_ONE_TEXT_MESSAGE',
    RECEIVE_GROUP_TEXT_MESSAGE='RECEIVE_GROUP_TEXT_MESSAGE'
}