package com.chatsync.chatSyncBackend.WSUtils;

public enum WSNotificationTypes {
    SENT_ONE_TO_ONE_TEXT_MESSAGE,
    RECEIVE_ONE_TO_ONE_TEXT_CONFIRM,
    SENT_GROUP_TEXT_MESSAGE,
    RECEIVE_ONE_TO_ONE_TEXT_MESSAGE,
    RECEIVE_GROUP_TEXT_MESSAGE,
    RECEIVE_GROUP_TEXT_MESSAGE_CONFIRM,
}
